# Generated by Django 4.2.1 on 2024-07-17 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('fastest_lap', models.CharField(max_length=10)),
                ('slowest_lap', models.CharField(max_length=10)),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f1app.circuit')),
            ],
        ),
        migrations.CreateModel(
            name='DriverStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.CharField(max_length=100)),
                ('driver_name', models.CharField(max_length=100)),
                ('constructor', models.CharField(max_length=100)),
                ('grid_position', models.IntegerField()),
                ('final_position', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('max_avg_speed', models.FloatField(blank=True, null=True)),
                ('min_avg_speed', models.FloatField(blank=True, null=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f1app.race')),
            ],
        ),
    ]
