# Generated by Django 4.2.1 on 2024-07-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='fastest_lap',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='race',
            name='slowest_lap',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
