# Generated by Django 4.2.1 on 2024-07-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1app', '0002_alter_race_fastest_lap_alter_race_slowest_lap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='fastest_lap',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='slowest_lap',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
